name: API Build & Test

on:
  workflow_call:
    secrets:
      MSSQL_SA_PASSWORD:
        required: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      MSSQL_SA_PASSWORD: ${{ secrets.MSSQL_SA_PASSWORD }}

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2025-latest
        env:
          ACCEPT_EULA: Y
          MSSQL_SA_PASSWORD: ${{ env.MSSQL_SA_PASSWORD }}
        ports:
          - 1433:1433
        options: >-
          --health-cmd "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P '${{ env.MSSQL_SA_PASSWORD }}' -C -Q 'SELECT 1' || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore ProcureHub.sln

      - name: Build
        run: dotnet build ProcureHub.sln --no-restore --configuration Release

      - name: Test
        run: dotnet test ProcureHub.sln --no-build --configuration Release --verbosity normal --logger "trx;LogFileName=ProcureHubTests.trx"  --results-directory ./TestResults
        env:
          ConnectionStrings__DefaultConnection: "Server=localhost;Database=procurehub_tests;User Id=sa;Password=${{ env.MSSQL_SA_PASSWORD }};TrustServerCertificate=true"

      - name: Test Report
        uses: dorny/test-reporter@v2
        if: ${{ !cancelled() }} # run this step even if previous step failed
        with:
          name: Test Report
          path: TestResults/*.trx
          reporter: dotnet-trx
