name: API CI

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'ProcureHub/**'
      - 'ProcureHub.WebApi/**'
      - 'ProcureHub.WebApi.Tests/**'
      - '.github/workflows/api-build-and-test.yml'
      - '.github/workflows/api-ci.yml'
  pull_request:
    branches: [main]
    paths:
      - 'ProcureHub/**'
      - 'ProcureHub.WebApi/**'
      - 'ProcureHub.WebApi.Tests/**'
      - '.github/workflows/api-build-and-test.yml'
      - '.github/workflows/api-ci.yml'

jobs:
  build-and-test:
    uses: ./.github/workflows/api-build-and-test.yml
    secrets: inherit

